"""
backend/app/routers/patients.py

REST endpoints for patient CRUD operations.

Router prefix : /api/patients
Tags          : patients

Endpoints
---------
POST   /          Add patient to queue; token is auto-generated (= Patient.id).
GET    /          List patients; supports ?status= filter.
GET    /{id}      Fetch single patient detail.
DELETE /{id}      Soft-delete: mark patient as no_show (no physical row removal).

State transitions initiated here
---------------------------------
  waiting → no_show  (DELETE /{id} — cancel a waiting patient)

Broadcast hook
--------------
Every state-changing endpoint calls broadcast_queue_update(db) after commit.
In Phase 2 this is a no-op stub.  Phase 3 replaces the stub body with the
real WebSocket fan-out without touching these call sites.
"""

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app.database import get_db
from app.models import Patient, PatientStatus, QueueSettings
from app.schemas import PatientCreate, PatientListResponse, PatientResponse
from app.websocket_manager import broadcast_queue_update

router = APIRouter(prefix="/api/patients", tags=["patients"])


# ---------------------------------------------------------------------------
# POST /api/patients  — add patient
# ---------------------------------------------------------------------------


@router.post(
    "/",
    response_model=PatientResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Add patient to queue",
    description=(
        "Registers a new patient and assigns them the next available token number "
        "(auto-generated by the database as Patient.id).  The patient is placed at "
        "the end of the waiting queue."
    ),
)
def add_patient(payload: PatientCreate, db: Session = Depends(get_db)) -> PatientResponse:
    """
    Create a new patient row with status='waiting'.

    The token number is Patient.id — set by SQLite AUTOINCREMENT, never by
    application code, eliminating any concurrent-insert race.

    After committing, QueueSettings.last_token_issued is updated to the new
    patient's id so the receptionist dashboard always knows the highest token
    issued without querying the patients table.
    """
    patient = Patient(
        name=payload.name.strip(),
        phone=payload.phone.strip() if payload.phone else None,
        status=PatientStatus.WAITING.value,
        # created_at defaults to _utcnow() via the model column default
    )
    db.add(patient)
    db.flush()  # Flush to get the auto-generated id before committing

    # Keep last_token_issued in sync (informational — not used for generation)
    settings = db.get(QueueSettings, 1)
    if settings and patient.id > settings.last_token_issued:
        settings.last_token_issued = patient.id

    db.commit()
    db.refresh(patient)

    # Notify all WebSocket clients (no-op in Phase 2; real in Phase 3)
    broadcast_queue_update(db)

    return PatientResponse.model_validate(patient)


# ---------------------------------------------------------------------------
# GET /api/patients  — list patients
# ---------------------------------------------------------------------------


@router.get(
    "/",
    response_model=PatientListResponse,
    summary="List all patients",
    description=(
        "Returns all patients.  Use the optional ``status`` query parameter to "
        "filter by lifecycle state: waiting, in_consultation, completed, no_show."
    ),
)
def list_patients(
    status_filter: Optional[str] = Query(
        None,
        alias="status",
        description="Filter by patient status (waiting|in_consultation|completed|no_show).",
    ),
    db: Session = Depends(get_db),
) -> PatientListResponse:
    """
    List patients, optionally filtered by status.

    Results are ordered by created_at ascending (earliest first) so the queue
    table renders in the correct service order.

    A 400 is returned if an unrecognised status string is supplied — this
    prevents silent empty results that look like the queue is empty when it
    isn't.
    """
    valid_statuses = {s.value for s in PatientStatus}

    if status_filter is not None and status_filter not in valid_statuses:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                f"Invalid status filter '{status_filter}'. "
                f"Valid values: {sorted(valid_statuses)}"
            ),
        )

    query = db.query(Patient)
    if status_filter is not None:
        query = query.filter(Patient.status == status_filter)

    patients = query.order_by(Patient.created_at.asc()).all()

    return PatientListResponse(
        patients=[PatientResponse.model_validate(p) for p in patients],
        total=len(patients),
    )


# ---------------------------------------------------------------------------
# GET /api/patients/{patient_id}  — single patient
# ---------------------------------------------------------------------------


@router.get(
    "/{patient_id}",
    response_model=PatientResponse,
    summary="Get single patient",
    description="Fetch the full details of one patient by their id (token number).",
)
def get_patient(patient_id: int, db: Session = Depends(get_db)) -> PatientResponse:
    """Return one patient or 404 if not found."""
    patient = db.get(Patient, patient_id)
    if patient is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Patient {patient_id} not found.",
        )
    return PatientResponse.model_validate(patient)


# ---------------------------------------------------------------------------
# DELETE /api/patients/{patient_id}  — soft-delete / cancel
# ---------------------------------------------------------------------------


@router.delete(
    "/{patient_id}",
    response_model=PatientResponse,
    summary="Cancel patient (mark as no_show)",
    description=(
        "Soft-deletes a patient by marking them as no_show.  The row is never "
        "physically removed so token history is preserved.  "
        "Only patients with status='waiting' can be cancelled this way; "
        "a patient already in_consultation should be handled via "
        "POST /api/queue/no-show instead."
    ),
)
def cancel_patient(
    patient_id: int, db: Session = Depends(get_db)
) -> PatientResponse:
    """
    Mark a waiting patient as no_show.

    Business rules:
    - 404 if patient does not exist.
    - 409 if patient is already in_consultation, completed, or no_show.
      Use POST /api/queue/no-show for in_consultation patients.
    """
    patient = db.get(Patient, patient_id)
    if patient is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Patient {patient_id} not found.",
        )

    if patient.status != PatientStatus.WAITING.value:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                f"Cannot cancel patient {patient_id}: "
                f"current status is '{patient.status}'. "
                "Only 'waiting' patients can be cancelled here. "
                "For in_consultation patients use POST /api/queue/no-show."
            ),
        )

    patient.status = PatientStatus.NO_SHOW.value
    db.commit()
    db.refresh(patient)

    # Notify WebSocket clients (no-op in Phase 2)
    broadcast_queue_update(db)

    return PatientResponse.model_validate(patient)
